import assert from 'node:assert/strict';
import test from 'node:test';
import * as fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Journal, createRun, remaining, summary, prune } from '../dist/journal.js';
import { recoveryChoices, canFallback } from '../dist/workflows.js';
import { validateTask } from '../dist/task.js';
import { proposeRecipe, approveRecipe, applyRecipe, quarantineRecipe } from '../dist/recipes.js';

const task={url:'https://example.com/settings',goal:'Save the supplied name',inputs:{name:'New value'},steps:[{kind:'fill',selector:'#name',valueFromInput:'name',safeToRepeat:true},{kind:'click',selector:'#save'}],preconditions:[{kind:'text',selector:'#tenant',value:'Test tenant'}],checks:[{kind:'value',selector:'#name',value:'New value'}],name:'Settings'};
const cp={documentId:'doc1',fingerprint:'state1',url:task.url,at:1};
function local(t, input=task) {const root=fs.mkdtempSync(path.join(os.tmpdir(),'fe2e-record-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,j:createRun(root,input,true,'/dedicated/profile').journal};}
function blocked(j){j.append('attempt.start',{mode:'new',engine:'jev',allocatedMs:1000});j.append('target',{targetId:'owned',browserId:'browser'});j.append('checkpoint',cp);j.append('attempt.end',{status:'blocked',reasonCode:'interrupted',reason:'Interrupted',durationMs:100});}

test('request deduplication never starts a second run; changed input conflicts',t=>{const {root}=local(t);const a=createRun(root,{...task,requestId:'request1'},true,'/profile');const b=createRun(root,{...task,requestId:'request1'},true,'/profile');assert.equal(a.journal.runId,b.journal.runId);assert.equal(b.duplicate,true);assert.throws(()=>createRun(root,{...task,requestId:'request1',goal:'different'},true,'/profile'),/different inputs/)});
test('durable dispatch survives a torn final receipt and remains uncertain',t=>{const {j}=local(t);blocked(j);j.append('action.start',{id:'save',kind:'click',step:1,safeToRepeat:false});fs.appendFileSync(j.file,'{"torn":');assert.equal(new Journal(j.root,j.runId).state().pendingAction,'save');assert.deepEqual(recoveryChoices(j.state(),cp),['inspect','reconcile']);j.append('diagnosis',{});assert.equal(j.state().pendingAction,'save');assert.throws(()=>new Journal(j.root,'../escape'));});
test('acknowledgement is not verification and a different document cannot silently resume',t=>{const {j}=local(t);blocked(j);j.append('action.start',{id:'save',safeToRepeat:false});j.append('action.end',{id:'save'});assert.equal(j.state().status,'blocked');assert.deepEqual(recoveryChoices(j.state(),{...cp,documentId:'reloaded'}),['inspect','reconcile']);assert.equal(canFallback(0,j.state(),'engine_blocked'),false)});
test('lost repeat-safe state offers explicit reconstruction, not imaginary continuation',t=>{const input={...task,recovery:{restartSafe:true,reconstruct:[{kind:'navigate',value:task.url,safeToRepeat:true}]}};const {j}=local(t,input);blocked(j);j.append('action.start',{id:'fill',step:0,safeToRepeat:true});assert.deepEqual(recoveryChoices(j.state(),null),['reconstruct','restart']);j.append('safe_repeat',{mode:'reconstruct'});assert.equal(j.state().pendingAction,null);assert.equal(j.state().actionsUsed,1)});
test('failed and passed tests never become automatic replay candidates',t=>{const {j}=local(t);blocked(j);for(const status of ['failed','passed']){j.append('attempt.end',{status,reasonCode:'result',durationMs:100});assert.deepEqual(recoveryChoices(j.state(),cp),['inspect','verify'])}});
test('completed reconciliation advances a known step once and preserves its original failure',t=>{const {j}=local(t);blocked(j);j.append('action.start',{id:'save',step:1,safeToRepeat:false});j.append('reconciled',{outcome:'completed',nextStep:2});assert.equal(j.state().nextStep,2);assert.equal(j.state().pendingAction,null);assert.equal(j.state().status,'blocked');assert.equal(j.state().hasUnsafeActions,true)});
test('budgets accumulate across recovery and verification without using unknown cost as zero',t=>{const {j}=local(t);blocked(j);j.append('call.start',{engine:'jev'});j.append('attempt.start',{mode:'resume',engine:'jev',allocatedMs:1000});j.append('attempt.end',{status:'done',durationMs:150,reasonCode:'complete'});j.append('observation.time',{durationMs:50});const s=j.state();assert.equal(s.activeMs,300);assert.equal(remaining(s).modelCalls,59);assert.equal(summary(s).budget.modelCost.kind,'unknown');assert.equal(s.recovered,true)});
test('recovery payloads are allowlisted, private and omitted from summaries',t=>{const {j}=local(t,{...task,recovery:{fields:[{key:'name',selector:'#name'}]}});j.saveField('name','private form value','intent');assert.throws(()=>j.saveField('other','bad','intent'));assert.equal(fs.statSync(path.join(j.dir,'recovery.json')).mode&0o777,0o600);assert.ok(!JSON.stringify(summary(j.state())).includes('private form value'));assert.equal(j.recoveryFields().name.source,'intent')});
test('expired runs cannot execute and prune deletes their retained payload',t=>{const {j,root}=local(t);const m=j.meta();fs.writeFileSync(path.join(j.dir,'task.json'),JSON.stringify({...m,expiresAt:0}));assert.throws(()=>j.meta(),/expired/);assert.equal(prune(root),1);assert.ok(!fs.existsSync(j.dir));assert.equal(prune(root),0)});
test('reconstruction and reconciliation require explicit bounded input contracts',()=>{assert.throws(()=>validateTask({...task,recovery:{reconstruct:[{kind:'fill',selector:'#name',value:'x'}]}},true));assert.throws(()=>validateTask({...task,recovery:{reconcile:[{kind:'text',value:'Saved'}]}},true));assert.throws(()=>validateTask({...task,inputs:{}},true));validateTask(task,true)});
test('recipes require review and a distinct trial, use current inputs and inherit no repeat permission',t=>{const {root,j}=local(t);j.append('attempt.end',{status:'passed',durationMs:1,reasonCode:'complete'});const candidate=proposeRecipe(root,j.runId,'save-name');assert.equal(candidate.state,'candidate');assert.ok(candidate.steps.every(s=>s.safeToRepeat===undefined));assert.throws(()=>applyRecipe(root,{...task,steps:undefined,recipe:'save-name'}),/unapproved/);assert.throws(()=>approveRecipe(root,'save-name',j.runId));const trial=createRun(root,{...task,inputs:{name:'Other value'}},true,'/dedicated/profile').journal;trial.append('attempt.end',{status:'passed',durationMs:1,reasonCode:'complete'});approveRecipe(root,'save-name',trial.runId);const applied=applyRecipe(root,{...task,steps:undefined,recipe:'save-name',inputs:{name:'Today'}});assert.equal(applied.inputs.name,'Today');assert.equal(applied.steps[0].value,undefined);assert.throws(()=>applyRecipe(root,{...task,steps:undefined,recipe:'save-name',url:'https://other.example/settings'}));quarantineRecipe(root,'save-name','changed UI');assert.throws(()=>applyRecipe(root,{...task,steps:undefined,recipe:'save-name'}),/quarantined/)});
